### ISSUE TITLE
[#4] Realtime DataBaseへサンプルデータの追加・削除・更新

### ISSUE THREAD

**Issue by takuma-ru** [takuma-ru/Fascino#16]
**11/9 更新**
- ToDo
  nuxt/firebaseを用いて、[サンプルデータ](asd)の:**追加**・**削除**・**更新**処理を実装する
  - [x] データの**追加**処理
  - [x] データの**削除**処理
  - [x] データの**取得**処理
    - [x] 10件毎で取得する(1-10, 11-20って出来るように)
    - [x] uidで検索をかけて取得
  - [x] likesSumのインクリメント・デクリメント処理の実装

**Comment by takuma-ru** [comment]
11/2
- get処理
- ミューテーション

**Comment by takuma-ru** [comment]
@citron192 
更新した
