### ISSUE TITLE
~ ユーザーが押した「いいね」「行きたい」投稿データをもとに押せるかどうか判定する ~

### ISSUE THREAD

**Issue by takuma-ru** [takuma-ru/Fascino#36]
**処理の流れ**
1. 画面読み込み時にFirestoreからそのユーザーがすでにいいねを押したPostDataIDのリスト(likedPostDataID)を取得
2. そのリストに表示するPostDataIDが入っているかを判定し、いいねボタンの表示状態を切り替える
  == いいね済み場合 ==
  3. RealtimeDatabaseにある対象のPostDataのlikesSumを**デクリメント**
  4. likedPostDataIDから対象のPostDataIDを削除
  5. 再度配列を取得
  == いいねしていない場合 ==
  3. RealtimeDatabaseにある対象のPostDataのlikesSumを**インクリメント**
  4. likedPostDataIDに対象のPostDataIDを追加
  5. 再度配列を取得

**Comment by takuma-ru** [comment]
- ToDo
  @Leggie1145 
  - [ ] 引数に指定されたPostDataID(String)を各ユーザードキュメントの**likedPostDataID**(配列)に追加する処理の実装
  - [ ] 引数に指定されたPostDataIDを各ユーザードキュメントの**likedPostDataID**から削除する処理の実装
  - [ ] likedPostDataIDを取得する処理の実装

  @citron192 
  - [ ] 上記の関数を使用し、いいねの関数にlikedPostDataIDにPostDataIDを追加、削除する処理を追加

**上記と同様な方法で行きたいボタンを押した際にも同じような動作をする処理の実装**

> **memo**
> likedPostDataID：いいねを押した投稿のIDを保存する配列
> wentPostDataID：行きたいを押した投稿のIDを保存する配列

**Comment by takuma-ru** [comment]
RTDBですべてを実装する為、Closeする。
